/**
 * Bundles the Supabase Edge Function "rodemap-mochi" into one file that the Supabase
 * runtime (Deno) can run: the shared Mochi modules from src/ are inlined and the Claude SDK
 * is loaded as npm:@anthropic-ai/sdk@<the version in package-lock>.
 *
 *   npm run build:supabase   → dist-supabase/rodemap-mochi/index.ts
 *
 * Deploy that file as the function's index.ts (Supabase CLI or dashboard), with JWT
 * verification on; the Rodemap Worker sends the project's anon key.
 */
import { build, type Plugin } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

const ENTRY = 'supabase/functions/rodemap-mochi/index.ts';
const OUT_DIR = 'dist-supabase/rodemap-mochi';

const sdk = JSON.parse(await readFile('node_modules/@anthropic-ai/sdk/package.json', 'utf8')) as { version: string };

/** Leaves the SDK as an npm: import for Deno instead of inlining it. */
const npmSpecifiers: Plugin = {
  name: 'npm-specifiers',
  setup(b) {
    b.onResolve({ filter: /^@anthropic-ai\/sdk$/ }, () => ({ path: `npm:@anthropic-ai/sdk@${sdk.version}`, external: true }));
  },
};

const result = await build({
  entryPoints: [ENTRY],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  write: false,
  legalComments: 'none',
  charset: 'utf8',
  plugins: [npmSpecifiers],
});

const code = result.outputFiles[0]?.text;
if (code === undefined) throw new Error('esbuild produced no output');
const banner = `// Generated by scripts/build-supabase-function.ts from ${ENTRY}. Do not edit; rebuild instead.\n`;
await mkdir(OUT_DIR, { recursive: true });
await writeFile(`${OUT_DIR}/index.ts`, banner + code);
console.warn(`build-supabase-function: wrote ${OUT_DIR}/index.ts (${String(Math.round(code.length / 1024))} KB, @anthropic-ai/sdk@${sdk.version})`);
